const countries = [
  { name: 'United Arab Emirates', code: 'ae' },
  { name: 'Argentina', code: 'ar' },
  { name: 'Australia', code: 'au' },
  { name: 'Belgium', code: 'be' },
  { name: 'Bulgaria', code: 'bg' },
  { name: 'Brazil', code: 'br' },
  { name: 'Canada', code: 'ca' },
  { name: 'Switzerland', code: 'ch' },
  { name: 'China', code: 'cn' },
  { name: 'Colombia', code: 'co' },
  { name: 'Czech Republic', code: 'cz' },
  { name: 'Germany', code: 'de' },
  { name: 'Egypt', code: 'eg' },
  { name: 'Spain', code: 'es' },
  { name: 'France', code: 'fr' },
  { name: 'United Kingdom', code: 'gb' },
  { name: 'Greece', code: 'gr' },
  { name: 'Hong Kong', code: 'hk' },
  { name: 'Hungary', code: 'hu' },
  { name: 'Indonesia', code: 'id' },
  { name: 'Ireland', code: 'ie' },
  { name: 'Israel', code: 'il' },
  { name: 'India', code: 'in' },
  { name: 'Italy', code: 'it' },
  { name: 'Japan', code: 'jp' },
  { name: 'South Korea', code: 'kr' },
  { name: 'Lebanon', code: 'lb' },
  { name: 'Luxembourg', code: 'lu' },
  { name: 'Macao', code: 'mo' },
  { name: 'Mexico', code: 'mx' },
  { name: 'Malaysia', code: 'my' },
  { name: 'Netherlands', code: 'nl' },
  { name: 'New Zealand', code: 'nz' },
  { name: 'Philippines', code: 'ph' },
  { name: 'Poland', code: 'pl' },
  { name: 'Portugal', code: 'pt' },
  { name: 'Puerto Rico', code: 'pr' },
  { name: 'Qatar', code: 'qa' },
  { name: 'Romania', code: 'ro' },
  { name: 'Russia', code: 'ru' },
  { name: 'Saudi Arabia', code: 'sa' },
  { name: 'Sweden', code: 'se' },
  { name: 'Singapore', code: 'sg' },
  { name: 'Slovenia', code: 'si' },
  { name: 'Slovakia', code: 'sk' },
  { name: 'Thailand', code: 'th' },
  { name: 'Turkey', code: 'tr' },
  { name: 'Taiwan', code: 'tw' },
  { name: 'Ukraine', code: 'ua' },
  { name: 'United States', code: 'us' },
  { name: 'Venezuela', code: 've' },
  { name: 'South Africa', code: 'za' }
];

const categories = [
  'Business', 'Entertainment', 'General', 'Health', 'Science', 'Sports', 'Technology'
];
const languages = [
  { name: 'Arabic', code: 'ar' },
  { name: 'German', code: 'de' },
  { name: 'English', code: 'en' },
  { name: 'Spanish', code: 'es' },
  { name: 'French', code: 'fr' },
  { name: 'Hebrew', code: 'he' },
  { name: 'Italian', code: 'it' },
  { name: 'Dutch', code: 'nl' },
  { name: 'Norwegian', code: 'no' },
  { name: 'Portuguese', code: 'pt' },
  { name: 'Russian', code: 'ru' },
  { name: 'Ukrainian', code: 'ua' },
  { name: 'Chinese', code: 'zh' }
];



export {countries,categories,languages};